/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Device
    /// </summary>
    [DataContract]
    public partial class Device :  IEquatable<Device>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Device" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Device() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Device" /> class.
        /// </summary>
        /// <param name="Imei">Imei (required).</param>
        /// <param name="Iccid">Iccid (required).</param>
        /// <param name="Imsi">Imsi.</param>
        /// <param name="BtMacAddress">BtMacAddress.</param>
        /// <param name="Type">Type.</param>
        /// <param name="LastConnection">LastConnection.</param>
        /// <param name="FirstSeen">FirstSeen (required).</param>
        /// <param name="Mode">Mode (required) (default to &quot;default&quot;).</param>
        /// <param name="Name">Name.</param>
        /// <param name="BatteryVoltage">BatteryVoltage.</param>
        /// <param name="BatteryType">BatteryType (default to &quot;LIO&quot;).</param>
        /// <param name="Tags">Tags.</param>
        /// <param name="CurrentMode">CurrentMode.</param>
        /// <param name="Color">Color (default to &quot;ce0027&quot;).</param>
        /// <param name="SaveToWeb">SaveToWeb (default to false).</param>
        /// <param name="Expires">Expires.</param>
        /// <param name="Active">Active (default to false).</param>
        /// <param name="DeepSleep">DeepSleep (default to false).</param>
        /// <param name="Simstate">Simstate (default to &quot;active&quot;).</param>
        /// <param name="Id">Id.</param>
        /// <param name="OwnerId">OwnerId.</param>
        /// <param name="SecurePhoneId">SecurePhoneId.</param>
        public Device(string Imei = default(string), string Iccid = default(string), string Imsi = default(string), string BtMacAddress = default(string), string Type = default(string), DateTime? LastConnection = default(DateTime?), DateTime? FirstSeen = default(DateTime?), string Mode = "default", string Name = default(string), decimal? BatteryVoltage = default(decimal?), string BatteryType = "LIO", List<string> Tags = default(List<string>), decimal? CurrentMode = default(decimal?), string Color = "ce0027", bool? SaveToWeb = false, DateTime? Expires = default(DateTime?), bool? Active = false, bool? DeepSleep = false, string Simstate = "active", decimal? Id = default(decimal?), decimal? OwnerId = default(decimal?), decimal? SecurePhoneId = default(decimal?))
        {
            // to ensure "Imei" is required (not null)
            if (Imei == null)
            {
                throw new InvalidDataException("Imei is a required property for Device and cannot be null");
            }
            else
            {
                this.Imei = Imei;
            }
            // to ensure "Iccid" is required (not null)
            if (Iccid == null)
            {
                throw new InvalidDataException("Iccid is a required property for Device and cannot be null");
            }
            else
            {
                this.Iccid = Iccid;
            }
            // to ensure "FirstSeen" is required (not null)
            if (FirstSeen == null)
            {
                throw new InvalidDataException("FirstSeen is a required property for Device and cannot be null");
            }
            else
            {
                this.FirstSeen = FirstSeen;
            }
            // to ensure "Mode" is required (not null)
            if (Mode == null)
            {
                throw new InvalidDataException("Mode is a required property for Device and cannot be null");
            }
            else
            {
                this.Mode = Mode;
            }
            this.Imsi = Imsi;
            this.BtMacAddress = BtMacAddress;
            this.Type = Type;
            this.LastConnection = LastConnection;
            this.Name = Name;
            this.BatteryVoltage = BatteryVoltage;
            // use default value if no "BatteryType" provided
            if (BatteryType == null)
            {
                this.BatteryType = "LIO";
            }
            else
            {
                this.BatteryType = BatteryType;
            }
            this.Tags = Tags;
            this.CurrentMode = CurrentMode;
            // use default value if no "Color" provided
            if (Color == null)
            {
                this.Color = "ce0027";
            }
            else
            {
                this.Color = Color;
            }
            // use default value if no "SaveToWeb" provided
            if (SaveToWeb == null)
            {
                this.SaveToWeb = false;
            }
            else
            {
                this.SaveToWeb = SaveToWeb;
            }
            this.Expires = Expires;
            // use default value if no "Active" provided
            if (Active == null)
            {
                this.Active = false;
            }
            else
            {
                this.Active = Active;
            }
            // use default value if no "DeepSleep" provided
            if (DeepSleep == null)
            {
                this.DeepSleep = false;
            }
            else
            {
                this.DeepSleep = DeepSleep;
            }
            // use default value if no "Simstate" provided
            if (Simstate == null)
            {
                this.Simstate = "active";
            }
            else
            {
                this.Simstate = Simstate;
            }
            this.Id = Id;
            this.OwnerId = OwnerId;
            this.SecurePhoneId = SecurePhoneId;
        }
        
        /// <summary>
        /// Gets or Sets Imei
        /// </summary>
        [DataMember(Name="imei", EmitDefaultValue=false)]
        public string Imei { get; set; }

        /// <summary>
        /// Gets or Sets Iccid
        /// </summary>
        [DataMember(Name="iccid", EmitDefaultValue=false)]
        public string Iccid { get; set; }

        /// <summary>
        /// Gets or Sets Imsi
        /// </summary>
        [DataMember(Name="imsi", EmitDefaultValue=false)]
        public string Imsi { get; set; }

        /// <summary>
        /// Gets or Sets BtMacAddress
        /// </summary>
        [DataMember(Name="btMacAddress", EmitDefaultValue=false)]
        public string BtMacAddress { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets LastConnection
        /// </summary>
        [DataMember(Name="lastConnection", EmitDefaultValue=false)]
        public DateTime? LastConnection { get; set; }

        /// <summary>
        /// Gets or Sets FirstSeen
        /// </summary>
        [DataMember(Name="firstSeen", EmitDefaultValue=false)]
        public DateTime? FirstSeen { get; set; }

        /// <summary>
        /// Gets or Sets Mode
        /// </summary>
        [DataMember(Name="mode", EmitDefaultValue=false)]
        public string Mode { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets BatteryVoltage
        /// </summary>
        [DataMember(Name="batteryVoltage", EmitDefaultValue=false)]
        public decimal? BatteryVoltage { get; set; }

        /// <summary>
        /// Gets or Sets BatteryType
        /// </summary>
        [DataMember(Name="batteryType", EmitDefaultValue=false)]
        public string BatteryType { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets CurrentMode
        /// </summary>
        [DataMember(Name="currentMode", EmitDefaultValue=false)]
        public decimal? CurrentMode { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name="color", EmitDefaultValue=false)]
        public string Color { get; set; }

        /// <summary>
        /// Gets or Sets SaveToWeb
        /// </summary>
        [DataMember(Name="saveToWeb", EmitDefaultValue=false)]
        public bool? SaveToWeb { get; set; }

        /// <summary>
        /// Gets or Sets Expires
        /// </summary>
        [DataMember(Name="expires", EmitDefaultValue=false)]
        public DateTime? Expires { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name="active", EmitDefaultValue=false)]
        public bool? Active { get; set; }

        /// <summary>
        /// Gets or Sets DeepSleep
        /// </summary>
        [DataMember(Name="deepSleep", EmitDefaultValue=false)]
        public bool? DeepSleep { get; set; }

        /// <summary>
        /// Gets or Sets Simstate
        /// </summary>
        [DataMember(Name="simstate", EmitDefaultValue=false)]
        public string Simstate { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public decimal? Id { get; set; }

        /// <summary>
        /// Gets or Sets OwnerId
        /// </summary>
        [DataMember(Name="ownerId", EmitDefaultValue=false)]
        public decimal? OwnerId { get; set; }

        /// <summary>
        /// Gets or Sets SecurePhoneId
        /// </summary>
        [DataMember(Name="securePhoneId", EmitDefaultValue=false)]
        public decimal? SecurePhoneId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Device {\n");
            sb.Append("  Imei: ").Append(Imei).Append("\n");
            sb.Append("  Iccid: ").Append(Iccid).Append("\n");
            sb.Append("  Imsi: ").Append(Imsi).Append("\n");
            sb.Append("  BtMacAddress: ").Append(BtMacAddress).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  LastConnection: ").Append(LastConnection).Append("\n");
            sb.Append("  FirstSeen: ").Append(FirstSeen).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  BatteryVoltage: ").Append(BatteryVoltage).Append("\n");
            sb.Append("  BatteryType: ").Append(BatteryType).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  CurrentMode: ").Append(CurrentMode).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  SaveToWeb: ").Append(SaveToWeb).Append("\n");
            sb.Append("  Expires: ").Append(Expires).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  DeepSleep: ").Append(DeepSleep).Append("\n");
            sb.Append("  Simstate: ").Append(Simstate).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  SecurePhoneId: ").Append(SecurePhoneId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Device);
        }

        /// <summary>
        /// Returns true if Device instances are equal
        /// </summary>
        /// <param name="input">Instance of Device to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Device input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Imei == input.Imei ||
                    (this.Imei != null &&
                    this.Imei.Equals(input.Imei))
                ) && 
                (
                    this.Iccid == input.Iccid ||
                    (this.Iccid != null &&
                    this.Iccid.Equals(input.Iccid))
                ) && 
                (
                    this.Imsi == input.Imsi ||
                    (this.Imsi != null &&
                    this.Imsi.Equals(input.Imsi))
                ) && 
                (
                    this.BtMacAddress == input.BtMacAddress ||
                    (this.BtMacAddress != null &&
                    this.BtMacAddress.Equals(input.BtMacAddress))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.LastConnection == input.LastConnection ||
                    (this.LastConnection != null &&
                    this.LastConnection.Equals(input.LastConnection))
                ) && 
                (
                    this.FirstSeen == input.FirstSeen ||
                    (this.FirstSeen != null &&
                    this.FirstSeen.Equals(input.FirstSeen))
                ) && 
                (
                    this.Mode == input.Mode ||
                    (this.Mode != null &&
                    this.Mode.Equals(input.Mode))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.BatteryVoltage == input.BatteryVoltage ||
                    (this.BatteryVoltage != null &&
                    this.BatteryVoltage.Equals(input.BatteryVoltage))
                ) && 
                (
                    this.BatteryType == input.BatteryType ||
                    (this.BatteryType != null &&
                    this.BatteryType.Equals(input.BatteryType))
                ) && 
                (
                    this.Tags == input.Tags ||
                    this.Tags != null &&
                    this.Tags.SequenceEqual(input.Tags)
                ) && 
                (
                    this.CurrentMode == input.CurrentMode ||
                    (this.CurrentMode != null &&
                    this.CurrentMode.Equals(input.CurrentMode))
                ) && 
                (
                    this.Color == input.Color ||
                    (this.Color != null &&
                    this.Color.Equals(input.Color))
                ) && 
                (
                    this.SaveToWeb == input.SaveToWeb ||
                    (this.SaveToWeb != null &&
                    this.SaveToWeb.Equals(input.SaveToWeb))
                ) && 
                (
                    this.Expires == input.Expires ||
                    (this.Expires != null &&
                    this.Expires.Equals(input.Expires))
                ) && 
                (
                    this.Active == input.Active ||
                    (this.Active != null &&
                    this.Active.Equals(input.Active))
                ) && 
                (
                    this.DeepSleep == input.DeepSleep ||
                    (this.DeepSleep != null &&
                    this.DeepSleep.Equals(input.DeepSleep))
                ) && 
                (
                    this.Simstate == input.Simstate ||
                    (this.Simstate != null &&
                    this.Simstate.Equals(input.Simstate))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.OwnerId == input.OwnerId ||
                    (this.OwnerId != null &&
                    this.OwnerId.Equals(input.OwnerId))
                ) && 
                (
                    this.SecurePhoneId == input.SecurePhoneId ||
                    (this.SecurePhoneId != null &&
                    this.SecurePhoneId.Equals(input.SecurePhoneId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Imei != null)
                    hashCode = hashCode * 59 + this.Imei.GetHashCode();
                if (this.Iccid != null)
                    hashCode = hashCode * 59 + this.Iccid.GetHashCode();
                if (this.Imsi != null)
                    hashCode = hashCode * 59 + this.Imsi.GetHashCode();
                if (this.BtMacAddress != null)
                    hashCode = hashCode * 59 + this.BtMacAddress.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.LastConnection != null)
                    hashCode = hashCode * 59 + this.LastConnection.GetHashCode();
                if (this.FirstSeen != null)
                    hashCode = hashCode * 59 + this.FirstSeen.GetHashCode();
                if (this.Mode != null)
                    hashCode = hashCode * 59 + this.Mode.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.BatteryVoltage != null)
                    hashCode = hashCode * 59 + this.BatteryVoltage.GetHashCode();
                if (this.BatteryType != null)
                    hashCode = hashCode * 59 + this.BatteryType.GetHashCode();
                if (this.Tags != null)
                    hashCode = hashCode * 59 + this.Tags.GetHashCode();
                if (this.CurrentMode != null)
                    hashCode = hashCode * 59 + this.CurrentMode.GetHashCode();
                if (this.Color != null)
                    hashCode = hashCode * 59 + this.Color.GetHashCode();
                if (this.SaveToWeb != null)
                    hashCode = hashCode * 59 + this.SaveToWeb.GetHashCode();
                if (this.Expires != null)
                    hashCode = hashCode * 59 + this.Expires.GetHashCode();
                if (this.Active != null)
                    hashCode = hashCode * 59 + this.Active.GetHashCode();
                if (this.DeepSleep != null)
                    hashCode = hashCode * 59 + this.DeepSleep.GetHashCode();
                if (this.Simstate != null)
                    hashCode = hashCode * 59 + this.Simstate.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.OwnerId != null)
                    hashCode = hashCode * 59 + this.OwnerId.GetHashCode();
                if (this.SecurePhoneId != null)
                    hashCode = hashCode * 59 + this.SecurePhoneId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Imei (string) maxLength
            if(this.Imei != null && this.Imei.Length > 15)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Imei, length must be less than 15.", new [] { "Imei" });
            }

            // BtMacAddress (string) maxLength
            if(this.BtMacAddress != null && this.BtMacAddress.Length > 17)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for BtMacAddress, length must be less than 17.", new [] { "BtMacAddress" });
            }

            yield break;
        }
    }

}
