/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Geofence
    /// </summary>
    [DataContract]
    public partial class Geofence :  IEquatable<Geofence>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Geofence" /> class.
        /// </summary>
        /// <param name="Outline">Array of {lat:x,lng:y} objects representing the vertices of the polygon.</param>
        /// <param name="Type">&#39;inside&#39;, &#39;outside&#39; or &#39;cross&#39;. For device safe-zone the value is ignored (always &#39;outside&#39;).</param>
        /// <param name="Name">Name.</param>
        /// <param name="WasInside">If the last point received was inside the geofence. Only updated for notifications (not the safe-zone as that is evaluated on the device) (default to false).</param>
        /// <param name="LastChecked">When the geofence was last evaluated. Only updated for notifications (not the safe-zone as that is evaluated on the device).</param>
        /// <param name="Modified">Modified (default to false).</param>
        /// <param name="Id">Id.</param>
        /// <param name="DeviceId">DeviceId.</param>
        /// <param name="ConfigId">ConfigId.</param>
        /// <param name="UserId">UserId.</param>
        public Geofence(List<Object> Outline = default(List<Object>), string Type = default(string), string Name = default(string), bool? WasInside = false, DateTime? LastChecked = default(DateTime?), bool? Modified = false, decimal? Id = default(decimal?), decimal? DeviceId = default(decimal?), decimal? ConfigId = default(decimal?), decimal? UserId = default(decimal?))
        {
            this.Outline = Outline;
            this.Type = Type;
            this.Name = Name;
            // use default value if no "WasInside" provided
            if (WasInside == null)
            {
                this.WasInside = false;
            }
            else
            {
                this.WasInside = WasInside;
            }
            this.LastChecked = LastChecked;
            // use default value if no "Modified" provided
            if (Modified == null)
            {
                this.Modified = false;
            }
            else
            {
                this.Modified = Modified;
            }
            this.Id = Id;
            this.DeviceId = DeviceId;
            this.ConfigId = ConfigId;
            this.UserId = UserId;
        }
        
        /// <summary>
        /// Array of {lat:x,lng:y} objects representing the vertices of the polygon
        /// </summary>
        /// <value>Array of {lat:x,lng:y} objects representing the vertices of the polygon</value>
        [DataMember(Name="outline", EmitDefaultValue=false)]
        public List<Object> Outline { get; set; }

        /// <summary>
        /// &#39;inside&#39;, &#39;outside&#39; or &#39;cross&#39;. For device safe-zone the value is ignored (always &#39;outside&#39;)
        /// </summary>
        /// <value>&#39;inside&#39;, &#39;outside&#39; or &#39;cross&#39;. For device safe-zone the value is ignored (always &#39;outside&#39;)</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// If the last point received was inside the geofence. Only updated for notifications (not the safe-zone as that is evaluated on the device)
        /// </summary>
        /// <value>If the last point received was inside the geofence. Only updated for notifications (not the safe-zone as that is evaluated on the device)</value>
        [DataMember(Name="wasInside", EmitDefaultValue=false)]
        public bool? WasInside { get; set; }

        /// <summary>
        /// When the geofence was last evaluated. Only updated for notifications (not the safe-zone as that is evaluated on the device)
        /// </summary>
        /// <value>When the geofence was last evaluated. Only updated for notifications (not the safe-zone as that is evaluated on the device)</value>
        [DataMember(Name="lastChecked", EmitDefaultValue=false)]
        public DateTime? LastChecked { get; set; }

        /// <summary>
        /// Gets or Sets Modified
        /// </summary>
        [DataMember(Name="modified", EmitDefaultValue=false)]
        public bool? Modified { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public decimal? Id { get; set; }

        /// <summary>
        /// Gets or Sets DeviceId
        /// </summary>
        [DataMember(Name="deviceId", EmitDefaultValue=false)]
        public decimal? DeviceId { get; set; }

        /// <summary>
        /// Gets or Sets ConfigId
        /// </summary>
        [DataMember(Name="configId", EmitDefaultValue=false)]
        public decimal? ConfigId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public decimal? UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Geofence {\n");
            sb.Append("  Outline: ").Append(Outline).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  WasInside: ").Append(WasInside).Append("\n");
            sb.Append("  LastChecked: ").Append(LastChecked).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  ConfigId: ").Append(ConfigId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Geofence);
        }

        /// <summary>
        /// Returns true if Geofence instances are equal
        /// </summary>
        /// <param name="input">Instance of Geofence to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Geofence input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Outline == input.Outline ||
                    this.Outline != null &&
                    this.Outline.SequenceEqual(input.Outline)
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.WasInside == input.WasInside ||
                    (this.WasInside != null &&
                    this.WasInside.Equals(input.WasInside))
                ) && 
                (
                    this.LastChecked == input.LastChecked ||
                    (this.LastChecked != null &&
                    this.LastChecked.Equals(input.LastChecked))
                ) && 
                (
                    this.Modified == input.Modified ||
                    (this.Modified != null &&
                    this.Modified.Equals(input.Modified))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.DeviceId == input.DeviceId ||
                    (this.DeviceId != null &&
                    this.DeviceId.Equals(input.DeviceId))
                ) && 
                (
                    this.ConfigId == input.ConfigId ||
                    (this.ConfigId != null &&
                    this.ConfigId.Equals(input.ConfigId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Outline != null)
                    hashCode = hashCode * 59 + this.Outline.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.WasInside != null)
                    hashCode = hashCode * 59 + this.WasInside.GetHashCode();
                if (this.LastChecked != null)
                    hashCode = hashCode * 59 + this.LastChecked.GetHashCode();
                if (this.Modified != null)
                    hashCode = hashCode * 59 + this.Modified.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.DeviceId != null)
                    hashCode = hashCode * 59 + this.DeviceId.GetHashCode();
                if (this.ConfigId != null)
                    hashCode = hashCode * 59 + this.ConfigId.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
