/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// NotificationTrigger
    /// </summary>
    [DataContract]
    public partial class NotificationTrigger :  IEquatable<NotificationTrigger>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationTrigger" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NotificationTrigger() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationTrigger" /> class.
        /// </summary>
        /// <param name="Name">Name (required).</param>
        /// <param name="Type">Type (required).</param>
        /// <param name="Parameters">Parameters.</param>
        /// <param name="MuteFor">MuteFor (required).</param>
        /// <param name="LastTriggered">LastTriggered.</param>
        /// <param name="Delivery">Delivery (required).</param>
        /// <param name="Id">Id.</param>
        /// <param name="DeviceId">DeviceId.</param>
        /// <param name="UserId">UserId.</param>
        public NotificationTrigger(string Name = default(string), string Type = default(string), Object Parameters = default(Object), decimal? MuteFor = default(decimal?), DateTime? LastTriggered = default(DateTime?), Object Delivery = default(Object), decimal? Id = default(decimal?), decimal? DeviceId = default(decimal?), decimal? UserId = default(decimal?))
        {
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for NotificationTrigger and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "Type" is required (not null)
            if (Type == null)
            {
                throw new InvalidDataException("Type is a required property for NotificationTrigger and cannot be null");
            }
            else
            {
                this.Type = Type;
            }
            // to ensure "MuteFor" is required (not null)
            if (MuteFor == null)
            {
                throw new InvalidDataException("MuteFor is a required property for NotificationTrigger and cannot be null");
            }
            else
            {
                this.MuteFor = MuteFor;
            }
            // to ensure "Delivery" is required (not null)
            if (Delivery == null)
            {
                throw new InvalidDataException("Delivery is a required property for NotificationTrigger and cannot be null");
            }
            else
            {
                this.Delivery = Delivery;
            }
            this.Parameters = Parameters;
            this.LastTriggered = LastTriggered;
            this.Id = Id;
            this.DeviceId = DeviceId;
            this.UserId = UserId;
        }
        
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Parameters
        /// </summary>
        [DataMember(Name="parameters", EmitDefaultValue=false)]
        public Object Parameters { get; set; }

        /// <summary>
        /// Gets or Sets MuteFor
        /// </summary>
        [DataMember(Name="muteFor", EmitDefaultValue=false)]
        public decimal? MuteFor { get; set; }

        /// <summary>
        /// Gets or Sets LastTriggered
        /// </summary>
        [DataMember(Name="lastTriggered", EmitDefaultValue=false)]
        public DateTime? LastTriggered { get; set; }

        /// <summary>
        /// Gets or Sets Delivery
        /// </summary>
        [DataMember(Name="delivery", EmitDefaultValue=false)]
        public Object Delivery { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public decimal? Id { get; set; }

        /// <summary>
        /// Gets or Sets DeviceId
        /// </summary>
        [DataMember(Name="deviceId", EmitDefaultValue=false)]
        public decimal? DeviceId { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name="userId", EmitDefaultValue=false)]
        public decimal? UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NotificationTrigger {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Parameters: ").Append(Parameters).Append("\n");
            sb.Append("  MuteFor: ").Append(MuteFor).Append("\n");
            sb.Append("  LastTriggered: ").Append(LastTriggered).Append("\n");
            sb.Append("  Delivery: ").Append(Delivery).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DeviceId: ").Append(DeviceId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NotificationTrigger);
        }

        /// <summary>
        /// Returns true if NotificationTrigger instances are equal
        /// </summary>
        /// <param name="input">Instance of NotificationTrigger to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NotificationTrigger input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Parameters == input.Parameters ||
                    (this.Parameters != null &&
                    this.Parameters.Equals(input.Parameters))
                ) && 
                (
                    this.MuteFor == input.MuteFor ||
                    (this.MuteFor != null &&
                    this.MuteFor.Equals(input.MuteFor))
                ) && 
                (
                    this.LastTriggered == input.LastTriggered ||
                    (this.LastTriggered != null &&
                    this.LastTriggered.Equals(input.LastTriggered))
                ) && 
                (
                    this.Delivery == input.Delivery ||
                    (this.Delivery != null &&
                    this.Delivery.Equals(input.Delivery))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.DeviceId == input.DeviceId ||
                    (this.DeviceId != null &&
                    this.DeviceId.Equals(input.DeviceId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Parameters != null)
                    hashCode = hashCode * 59 + this.Parameters.GetHashCode();
                if (this.MuteFor != null)
                    hashCode = hashCode * 59 + this.MuteFor.GetHashCode();
                if (this.LastTriggered != null)
                    hashCode = hashCode * 59 + this.LastTriggered.GetHashCode();
                if (this.Delivery != null)
                    hashCode = hashCode * 59 + this.Delivery.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.DeviceId != null)
                    hashCode = hashCode * 59 + this.DeviceId.GetHashCode();
                if (this.UserId != null)
                    hashCode = hashCode * 59 + this.UserId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
