/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Datapoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DatapointTests
    {
        // TODO uncomment below to declare an instance variable for Datapoint
        //private Datapoint instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Datapoint
            //instance = new Datapoint();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Datapoint
        /// </summary>
        [Test]
        public void DatapointInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Datapoint
            //Assert.IsInstanceOfType<Datapoint> (instance, "variable 'instance' is a Datapoint");
        }


        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Speed'
        /// </summary>
        [Test]
        public void SpeedTest()
        {
            // TODO unit test for the property 'Speed'
        }
        /// <summary>
        /// Test the property 'Altitude'
        /// </summary>
        [Test]
        public void AltitudeTest()
        {
            // TODO unit test for the property 'Altitude'
        }
        /// <summary>
        /// Test the property 'Course'
        /// </summary>
        [Test]
        public void CourseTest()
        {
            // TODO unit test for the property 'Course'
        }
        /// <summary>
        /// Test the property 'NumValue'
        /// </summary>
        [Test]
        public void NumValueTest()
        {
            // TODO unit test for the property 'NumValue'
        }
        /// <summary>
        /// Test the property 'StringValue'
        /// </summary>
        [Test]
        public void StringValueTest()
        {
            // TODO unit test for the property 'StringValue'
        }
        /// <summary>
        /// Test the property 'SendReason'
        /// </summary>
        [Test]
        public void SendReasonTest()
        {
            // TODO unit test for the property 'SendReason'
        }
        /// <summary>
        /// Test the property 'Sats'
        /// </summary>
        [Test]
        public void SatsTest()
        {
            // TODO unit test for the property 'Sats'
        }
        /// <summary>
        /// Test the property 'Hdop'
        /// </summary>
        [Test]
        public void HdopTest()
        {
            // TODO unit test for the property 'Hdop'
        }
        /// <summary>
        /// Test the property 'Accuracy'
        /// </summary>
        [Test]
        public void AccuracyTest()
        {
            // TODO unit test for the property 'Accuracy'
        }
        /// <summary>
        /// Test the property 'LocationType'
        /// </summary>
        [Test]
        public void LocationTypeTest()
        {
            // TODO unit test for the property 'LocationType'
        }
        /// <summary>
        /// Test the property 'BatteryVoltage'
        /// </summary>
        [Test]
        public void BatteryVoltageTest()
        {
            // TODO unit test for the property 'BatteryVoltage'
        }
        /// <summary>
        /// Test the property 'AverageCharge'
        /// </summary>
        [Test]
        public void AverageChargeTest()
        {
            // TODO unit test for the property 'AverageCharge'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'AlertType'
        /// </summary>
        [Test]
        public void AlertTypeTest()
        {
            // TODO unit test for the property 'AlertType'
        }
        /// <summary>
        /// Test the property 'CurrentUsed'
        /// </summary>
        [Test]
        public void CurrentUsedTest()
        {
            // TODO unit test for the property 'CurrentUsed'
        }
        /// <summary>
        /// Test the property 'GsmSignal'
        /// </summary>
        [Test]
        public void GsmSignalTest()
        {
            // TODO unit test for the property 'GsmSignal'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }

    }

}
