/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DeviceConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeviceConfigTests
    {
        // TODO uncomment below to declare an instance variable for DeviceConfig
        //private DeviceConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeviceConfig
            //instance = new DeviceConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeviceConfig
        /// </summary>
        [Test]
        public void DeviceConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeviceConfig
            //Assert.IsInstanceOfType<DeviceConfig> (instance, "variable 'instance' is a DeviceConfig");
        }


        /// <summary>
        /// Test the property 'CurrentFW'
        /// </summary>
        [Test]
        public void CurrentFWTest()
        {
            // TODO unit test for the property 'CurrentFW'
        }
        /// <summary>
        /// Test the property 'OtaFW'
        /// </summary>
        [Test]
        public void OtaFWTest()
        {
            // TODO unit test for the property 'OtaFW'
        }
        /// <summary>
        /// Test the property 'Interval'
        /// </summary>
        [Test]
        public void IntervalTest()
        {
            // TODO unit test for the property 'Interval'
        }
        /// <summary>
        /// Test the property 'SleepInterval'
        /// </summary>
        [Test]
        public void SleepIntervalTest()
        {
            // TODO unit test for the property 'SleepInterval'
        }
        /// <summary>
        /// Test the property 'CheckInInterval'
        /// </summary>
        [Test]
        public void CheckInIntervalTest()
        {
            // TODO unit test for the property 'CheckInInterval'
        }
        /// <summary>
        /// Test the property 'Packing'
        /// </summary>
        [Test]
        public void PackingTest()
        {
            // TODO unit test for the property 'Packing'
        }
        /// <summary>
        /// Test the property 'MovementSensitivity'
        /// </summary>
        [Test]
        public void MovementSensitivityTest()
        {
            // TODO unit test for the property 'MovementSensitivity'
        }
        /// <summary>
        /// Test the property 'Debounce'
        /// </summary>
        [Test]
        public void DebounceTest()
        {
            // TODO unit test for the property 'Debounce'
        }
        /// <summary>
        /// Test the property 'MovementSensitivity2'
        /// </summary>
        [Test]
        public void MovementSensitivity2Test()
        {
            // TODO unit test for the property 'MovementSensitivity2'
        }
        /// <summary>
        /// Test the property 'Behavior'
        /// </summary>
        [Test]
        public void BehaviorTest()
        {
            // TODO unit test for the property 'Behavior'
        }
        /// <summary>
        /// Test the property 'ModeControl'
        /// </summary>
        [Test]
        public void ModeControlTest()
        {
            // TODO unit test for the property 'ModeControl'
        }
        /// <summary>
        /// Test the property 'ModeControl2'
        /// </summary>
        [Test]
        public void ModeControl2Test()
        {
            // TODO unit test for the property 'ModeControl2'
        }
        /// <summary>
        /// Test the property 'GpsTimeout'
        /// </summary>
        [Test]
        public void GpsTimeoutTest()
        {
            // TODO unit test for the property 'GpsTimeout'
        }
        /// <summary>
        /// Test the property 'TransmitTimeout'
        /// </summary>
        [Test]
        public void TransmitTimeoutTest()
        {
            // TODO unit test for the property 'TransmitTimeout'
        }
        /// <summary>
        /// Test the property 'GpsStabilize'
        /// </summary>
        [Test]
        public void GpsStabilizeTest()
        {
            // TODO unit test for the property 'GpsStabilize'
        }
        /// <summary>
        /// Test the property 'GpsCheckInterval'
        /// </summary>
        [Test]
        public void GpsCheckIntervalTest()
        {
            // TODO unit test for the property 'GpsCheckInterval'
        }
        /// <summary>
        /// Test the property 'StopTimeout'
        /// </summary>
        [Test]
        public void StopTimeoutTest()
        {
            // TODO unit test for the property 'StopTimeout'
        }
        /// <summary>
        /// Test the property 'TolerancePercentage'
        /// </summary>
        [Test]
        public void TolerancePercentageTest()
        {
            // TODO unit test for the property 'TolerancePercentage'
        }
        /// <summary>
        /// Test the property 'ReasonsToWake'
        /// </summary>
        [Test]
        public void ReasonsToWakeTest()
        {
            // TODO unit test for the property 'ReasonsToWake'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'ForceFw'
        /// </summary>
        [Test]
        public void ForceFwTest()
        {
            // TODO unit test for the property 'ForceFw'
        }
        /// <summary>
        /// Test the property 'ReceivedAt'
        /// </summary>
        [Test]
        public void ReceivedAtTest()
        {
            // TODO unit test for the property 'ReceivedAt'
        }
        /// <summary>
        /// Test the property 'Reset'
        /// </summary>
        [Test]
        public void ResetTest()
        {
            // TODO unit test for the property 'Reset'
        }
        /// <summary>
        /// Test the property 'FlashTryCount'
        /// </summary>
        [Test]
        public void FlashTryCountTest()
        {
            // TODO unit test for the property 'FlashTryCount'
        }
        /// <summary>
        /// Test the property 'HomeWifiNetwork'
        /// </summary>
        [Test]
        public void HomeWifiNetworkTest()
        {
            // TODO unit test for the property 'HomeWifiNetwork'
        }
        /// <summary>
        /// Test the property 'HomeWifiPassword'
        /// </summary>
        [Test]
        public void HomeWifiPasswordTest()
        {
            // TODO unit test for the property 'HomeWifiPassword'
        }
        /// <summary>
        /// Test the property 'WakeAction'
        /// </summary>
        [Test]
        public void WakeActionTest()
        {
            // TODO unit test for the property 'WakeAction'
        }
        /// <summary>
        /// Test the property 'OnDemandTime'
        /// </summary>
        [Test]
        public void OnDemandTimeTest()
        {
            // TODO unit test for the property 'OnDemandTime'
        }
        /// <summary>
        /// Test the property 'AlertAction'
        /// </summary>
        [Test]
        public void AlertActionTest()
        {
            // TODO unit test for the property 'AlertAction'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'SafeZoneId'
        /// </summary>
        [Test]
        public void SafeZoneIdTest()
        {
            // TODO unit test for the property 'SafeZoneId'
        }

    }

}
