/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Geofence
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeofenceTests
    {
        // TODO uncomment below to declare an instance variable for Geofence
        //private Geofence instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Geofence
            //instance = new Geofence();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Geofence
        /// </summary>
        [Test]
        public void GeofenceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Geofence
            //Assert.IsInstanceOfType<Geofence> (instance, "variable 'instance' is a Geofence");
        }


        /// <summary>
        /// Test the property 'Outline'
        /// </summary>
        [Test]
        public void OutlineTest()
        {
            // TODO unit test for the property 'Outline'
        }
        /// <summary>
        /// Test the property 'Center'
        /// </summary>
        [Test]
        public void CenterTest()
        {
            // TODO unit test for the property 'Center'
        }
        /// <summary>
        /// Test the property 'Radius'
        /// </summary>
        [Test]
        public void RadiusTest()
        {
            // TODO unit test for the property 'Radius'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'WasInside'
        /// </summary>
        [Test]
        public void WasInsideTest()
        {
            // TODO unit test for the property 'WasInside'
        }
        /// <summary>
        /// Test the property 'LastChecked'
        /// </summary>
        [Test]
        public void LastCheckedTest()
        {
            // TODO unit test for the property 'LastChecked'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'ConfigId'
        /// </summary>
        [Test]
        public void ConfigIdTest()
        {
            // TODO unit test for the property 'ConfigId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
