/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GeoPoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeoPointTests
    {
        // TODO uncomment below to declare an instance variable for GeoPoint
        //private GeoPoint instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeoPoint
            //instance = new GeoPoint();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeoPoint
        /// </summary>
        [Test]
        public void GeoPointInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeoPoint
            //Assert.IsInstanceOfType<GeoPoint> (instance, "variable 'instance' is a GeoPoint");
        }


        /// <summary>
        /// Test the property 'Lat'
        /// </summary>
        [Test]
        public void LatTest()
        {
            // TODO unit test for the property 'Lat'
        }
        /// <summary>
        /// Test the property 'Lng'
        /// </summary>
        [Test]
        public void LngTest()
        {
            // TODO unit test for the property 'Lng'
        }

    }

}
