/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NotificationTrigger
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationTriggerTests
    {
        // TODO uncomment below to declare an instance variable for NotificationTrigger
        //private NotificationTrigger instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotificationTrigger
            //instance = new NotificationTrigger();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotificationTrigger
        /// </summary>
        [Test]
        public void NotificationTriggerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NotificationTrigger
            //Assert.IsInstanceOfType<NotificationTrigger> (instance, "variable 'instance' is a NotificationTrigger");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'MuteFor'
        /// </summary>
        [Test]
        public void MuteForTest()
        {
            // TODO unit test for the property 'MuteFor'
        }
        /// <summary>
        /// Test the property 'LastTriggered'
        /// </summary>
        [Test]
        public void LastTriggeredTest()
        {
            // TODO unit test for the property 'LastTriggered'
        }
        /// <summary>
        /// Test the property 'Delivery'
        /// </summary>
        [Test]
        public void DeliveryTest()
        {
            // TODO unit test for the property 'Delivery'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
