/* 
 * TrackingAPI
 *
 * API for retrieving tracking data and changing settings on LightBug & RemoteThings tracking devices
 *
 * OpenAPI spec version: 1.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Notification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NotificationTests
    {
        // TODO uncomment below to declare an instance variable for Notification
        //private Notification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Notification
            //instance = new Notification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Notification
        /// </summary>
        [Test]
        public void NotificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Notification
            //Assert.IsInstanceOfType<Notification> (instance, "variable 'instance' is a Notification");
        }


        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Test]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'DismissedOn'
        /// </summary>
        [Test]
        public void DismissedOnTest()
        {
            // TODO unit test for the property 'DismissedOn'
        }
        /// <summary>
        /// Test the property 'DismissedBy'
        /// </summary>
        [Test]
        public void DismissedByTest()
        {
            // TODO unit test for the property 'DismissedBy'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Test]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'PointId'
        /// </summary>
        [Test]
        public void PointIdTest()
        {
            // TODO unit test for the property 'PointId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'TriggerId'
        /// </summary>
        [Test]
        public void TriggerIdTest()
        {
            // TODO unit test for the property 'TriggerId'
        }

    }

}
